Clear marketplace cache during upgrade
openhab/openhab-linuxpkg pull request #227
Opened 2024-01-05 17:56 UTC by J-N-K

Related to https://github.com/openhab/openhab-core/pull/4019

2024-01-07 19:16 UTC, BClark09 requested changes
Thanks @J-N-K! With the suggested change should we wait until your PR in core is merged?

2024-01-07 19:16 UTC, BClark09 commented on resources/control-runtime/preinst
> +  [ -d ${UD_MARKETPLACE} ] && rm -rf ${UD_TMP}
```suggestion
  [ -d ${UD_MARKETPLACE} ] && rm -rf ${UD_MARKETPLACE}
```

2024-01-07 19:31 UTC, J-N-K commented
Correct, this will otherwise create issues.

2024-01-07 19:45 UTC, BClark09 approved these changes
Great, I'll watch the other PR and merge when appropriate. Thanks again!

2024-01-14 20:51 UTC, J-N-K commented
@BClark09 You can merge now

2024-01-14 21:48 UTC, merged